// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categoriaproducto.sql

package dto

import (
	"context"
	"database/sql"
)

const countProductosByCategoria = `-- name: CountProductosByCategoria :one
SELECT COUNT(*) FROM producto WHERE idCategoriaProducto = ?
`

func (q *Queries) CountProductosByCategoria(ctx context.Context, idcategoriaproducto int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductosByCategoria, idcategoriaproducto)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCategory = `-- name: DeleteCategory :execresult
DELETE FROM categoriaproducto WHERE idCategoriaProducto = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, idcategoriaproducto int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCategory, idcategoriaproducto)
}

const getAllCategoriaProducto = `-- name: GetAllCategoriaProducto :many
SELECT idcategoriaproducto, nombre, descripcion FROM categoriaproducto
`

func (q *Queries) GetAllCategoriaProducto(ctx context.Context) ([]Categoriaproducto, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategoriaProducto)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Categoriaproducto
	for rows.Next() {
		var i Categoriaproducto
		if err := rows.Scan(&i.Idcategoriaproducto, &i.Nombre, &i.Descripcion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriaProductoByID = `-- name: GetCategoriaProductoByID :one
SELECT idcategoriaproducto, nombre, descripcion FROM categoriaproducto WHERE idCategoriaProducto = ?
`

func (q *Queries) GetCategoriaProductoByID(ctx context.Context, idcategoriaproducto int32) (Categoriaproducto, error) {
	row := q.db.QueryRowContext(ctx, getCategoriaProductoByID, idcategoriaproducto)
	var i Categoriaproducto
	err := row.Scan(&i.Idcategoriaproducto, &i.Nombre, &i.Descripcion)
	return i, err
}

const searchCategoriaProductoByName = `-- name: SearchCategoriaProductoByName :many
SELECT idcategoriaproducto, nombre, descripcion FROM categoriaproducto WHERE nombre LIKE ? OR descripcion LIKE ?
`

type SearchCategoriaProductoByNameParams struct {
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
}

func (q *Queries) SearchCategoriaProductoByName(ctx context.Context, arg SearchCategoriaProductoByNameParams) ([]Categoriaproducto, error) {
	rows, err := q.db.QueryContext(ctx, searchCategoriaProductoByName, arg.Nombre, arg.Descripcion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Categoriaproducto
	for rows.Next() {
		var i Categoriaproducto
		if err := rows.Scan(&i.Idcategoriaproducto, &i.Nombre, &i.Descripcion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoriaProducto = `-- name: UpdateCategoriaProducto :execresult
UPDATE categoriaproducto SET nombre = ?, descripcion = ? WHERE idCategoriaProducto = ?
`

type UpdateCategoriaProductoParams struct {
	Nombre              string         `json:"nombre"`
	Descripcion         sql.NullString `json:"descripcion"`
	Idcategoriaproducto int32          `json:"idcategoriaproducto"`
}

func (q *Queries) UpdateCategoriaProducto(ctx context.Context, arg UpdateCategoriaProductoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCategoriaProducto, arg.Nombre, arg.Descripcion, arg.Idcategoriaproducto)
}
