// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compra.sql

package dto

import (
	"context"
	"database/sql"
	"time"
)

const createCompra = `-- name: CreateCompra :execresult
INSERT INTO compra (idMetodoPago, idUsuario, idProveedor, fecha, total)
VALUES (?, ?, ?, ?, ?)
`

type CreateCompraParams struct {
	Idmetodopago int32     `json:"idmetodopago"`
	Idusuario    int32     `json:"idusuario"`
	Idproveedor  int32     `json:"idproveedor"`
	Fecha        time.Time `json:"fecha"`
	Total        string    `json:"total"`
}

func (q *Queries) CreateCompra(ctx context.Context, arg CreateCompraParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCompra,
		arg.Idmetodopago,
		arg.Idusuario,
		arg.Idproveedor,
		arg.Fecha,
		arg.Total,
	)
}

const getAllCompras = `-- name: GetAllCompras :many
SELECT 
    c.idCompra,
    c.idMetodoPago,
    c.idUsuario,
    u.nombre as nombreUsuario,
    c.idProveedor,
    p.nombre as nombreProveedor,
    c.fecha,
    c.total
FROM compra c
INNER JOIN usuario u ON c.idUsuario = u.idUsuario
INNER JOIN proveedor p ON c.idProveedor = p.idProveedor
ORDER BY c.fecha DESC
`

type GetAllComprasRow struct {
	Idcompra        int32     `json:"idcompra"`
	Idmetodopago    int32     `json:"idmetodopago"`
	Idusuario       int32     `json:"idusuario"`
	Nombreusuario   string    `json:"nombreusuario"`
	Idproveedor     int32     `json:"idproveedor"`
	Nombreproveedor string    `json:"nombreproveedor"`
	Fecha           time.Time `json:"fecha"`
	Total           string    `json:"total"`
}

func (q *Queries) GetAllCompras(ctx context.Context) ([]GetAllComprasRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCompras)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllComprasRow
	for rows.Next() {
		var i GetAllComprasRow
		if err := rows.Scan(
			&i.Idcompra,
			&i.Idmetodopago,
			&i.Idusuario,
			&i.Nombreusuario,
			&i.Idproveedor,
			&i.Nombreproveedor,
			&i.Fecha,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompraById = `-- name: GetCompraById :one
SELECT 
    c.idCompra,
    c.idMetodoPago,
    c.idUsuario,
    u.nombre as nombreUsuario,
    c.idProveedor,
    p.nombre as nombreProveedor,
    c.fecha,
    c.total
FROM compra c
INNER JOIN usuario u ON c.idUsuario = u.idUsuario
INNER JOIN proveedor p ON c.idProveedor = p.idProveedor
WHERE c.idCompra = ?
`

type GetCompraByIdRow struct {
	Idcompra        int32     `json:"idcompra"`
	Idmetodopago    int32     `json:"idmetodopago"`
	Idusuario       int32     `json:"idusuario"`
	Nombreusuario   string    `json:"nombreusuario"`
	Idproveedor     int32     `json:"idproveedor"`
	Nombreproveedor string    `json:"nombreproveedor"`
	Fecha           time.Time `json:"fecha"`
	Total           string    `json:"total"`
}

func (q *Queries) GetCompraById(ctx context.Context, idcompra int32) (GetCompraByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getCompraById, idcompra)
	var i GetCompraByIdRow
	err := row.Scan(
		&i.Idcompra,
		&i.Idmetodopago,
		&i.Idusuario,
		&i.Nombreusuario,
		&i.Idproveedor,
		&i.Nombreproveedor,
		&i.Fecha,
		&i.Total,
	)
	return i, err
}

const getComprasByFecha = `-- name: GetComprasByFecha :many
SELECT 
    c.idCompra,
    c.idMetodoPago,
    c.idUsuario,
    u.nombre as nombreUsuario,
    c.idProveedor,
    p.nombre as nombreProveedor,
    c.fecha,
    c.total
FROM compra c
INNER JOIN usuario u ON c.idUsuario = u.idUsuario
INNER JOIN proveedor p ON c.idProveedor = p.idProveedor
WHERE c.fecha = ?
ORDER BY c.fecha DESC
`

type GetComprasByFechaRow struct {
	Idcompra        int32     `json:"idcompra"`
	Idmetodopago    int32     `json:"idmetodopago"`
	Idusuario       int32     `json:"idusuario"`
	Nombreusuario   string    `json:"nombreusuario"`
	Idproveedor     int32     `json:"idproveedor"`
	Nombreproveedor string    `json:"nombreproveedor"`
	Fecha           time.Time `json:"fecha"`
	Total           string    `json:"total"`
}

func (q *Queries) GetComprasByFecha(ctx context.Context, fecha time.Time) ([]GetComprasByFechaRow, error) {
	rows, err := q.db.QueryContext(ctx, getComprasByFecha, fecha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComprasByFechaRow
	for rows.Next() {
		var i GetComprasByFechaRow
		if err := rows.Scan(
			&i.Idcompra,
			&i.Idmetodopago,
			&i.Idusuario,
			&i.Nombreusuario,
			&i.Idproveedor,
			&i.Nombreproveedor,
			&i.Fecha,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComprasByFechaRange = `-- name: GetComprasByFechaRange :many
SELECT 
    c.idCompra,
    c.idMetodoPago,
    c.idUsuario,
    u.nombre as nombreUsuario,
    c.idProveedor,
    p.nombre as nombreProveedor,
    c.fecha,
    c.total
FROM compra c
INNER JOIN usuario u ON c.idUsuario = u.idUsuario
INNER JOIN proveedor p ON c.idProveedor = p.idProveedor
WHERE c.fecha BETWEEN ? AND ?
ORDER BY c.fecha DESC
`

type GetComprasByFechaRangeParams struct {
	FromFecha time.Time `json:"from_fecha"`
	ToFecha   time.Time `json:"to_fecha"`
}

type GetComprasByFechaRangeRow struct {
	Idcompra        int32     `json:"idcompra"`
	Idmetodopago    int32     `json:"idmetodopago"`
	Idusuario       int32     `json:"idusuario"`
	Nombreusuario   string    `json:"nombreusuario"`
	Idproveedor     int32     `json:"idproveedor"`
	Nombreproveedor string    `json:"nombreproveedor"`
	Fecha           time.Time `json:"fecha"`
	Total           string    `json:"total"`
}

func (q *Queries) GetComprasByFechaRange(ctx context.Context, arg GetComprasByFechaRangeParams) ([]GetComprasByFechaRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getComprasByFechaRange, arg.FromFecha, arg.ToFecha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComprasByFechaRangeRow
	for rows.Next() {
		var i GetComprasByFechaRangeRow
		if err := rows.Scan(
			&i.Idcompra,
			&i.Idmetodopago,
			&i.Idusuario,
			&i.Nombreusuario,
			&i.Idproveedor,
			&i.Nombreproveedor,
			&i.Fecha,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComprasByProveedor = `-- name: GetComprasByProveedor :many
SELECT 
    c.idCompra,
    c.idMetodoPago,
    c.idUsuario,
    u.nombre as nombreUsuario,
    c.idProveedor,
    p.nombre as nombreProveedor,
    c.fecha,
    c.total
FROM compra c
INNER JOIN usuario u ON c.idUsuario = u.idUsuario
INNER JOIN proveedor p ON c.idProveedor = p.idProveedor
WHERE c.idProveedor = ?
ORDER BY c.fecha DESC
`

type GetComprasByProveedorRow struct {
	Idcompra        int32     `json:"idcompra"`
	Idmetodopago    int32     `json:"idmetodopago"`
	Idusuario       int32     `json:"idusuario"`
	Nombreusuario   string    `json:"nombreusuario"`
	Idproveedor     int32     `json:"idproveedor"`
	Nombreproveedor string    `json:"nombreproveedor"`
	Fecha           time.Time `json:"fecha"`
	Total           string    `json:"total"`
}

func (q *Queries) GetComprasByProveedor(ctx context.Context, idproveedor int32) ([]GetComprasByProveedorRow, error) {
	rows, err := q.db.QueryContext(ctx, getComprasByProveedor, idproveedor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComprasByProveedorRow
	for rows.Next() {
		var i GetComprasByProveedorRow
		if err := rows.Scan(
			&i.Idcompra,
			&i.Idmetodopago,
			&i.Idusuario,
			&i.Nombreusuario,
			&i.Idproveedor,
			&i.Nombreproveedor,
			&i.Fecha,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComprasByProveedorNombre = `-- name: GetComprasByProveedorNombre :many
SELECT 
    c.idCompra,
    c.idMetodoPago,
    c.idUsuario,
    u.nombre as nombreUsuario,
    c.idProveedor,
    p.nombre as nombreProveedor,
    c.fecha,
    c.total
FROM compra c
INNER JOIN usuario u ON c.idUsuario = u.idUsuario
INNER JOIN proveedor p ON c.idProveedor = p.idProveedor
WHERE p.nombre LIKE ?
ORDER BY c.fecha DESC
`

type GetComprasByProveedorNombreRow struct {
	Idcompra        int32     `json:"idcompra"`
	Idmetodopago    int32     `json:"idmetodopago"`
	Idusuario       int32     `json:"idusuario"`
	Nombreusuario   string    `json:"nombreusuario"`
	Idproveedor     int32     `json:"idproveedor"`
	Nombreproveedor string    `json:"nombreproveedor"`
	Fecha           time.Time `json:"fecha"`
	Total           string    `json:"total"`
}

func (q *Queries) GetComprasByProveedorNombre(ctx context.Context, nombre string) ([]GetComprasByProveedorNombreRow, error) {
	rows, err := q.db.QueryContext(ctx, getComprasByProveedorNombre, nombre)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComprasByProveedorNombreRow
	for rows.Next() {
		var i GetComprasByProveedorNombreRow
		if err := rows.Scan(
			&i.Idcompra,
			&i.Idmetodopago,
			&i.Idusuario,
			&i.Nombreusuario,
			&i.Idproveedor,
			&i.Nombreproveedor,
			&i.Fecha,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComprasByUsuario = `-- name: GetComprasByUsuario :many
SELECT 
    c.idCompra,
    c.idMetodoPago,
    c.idUsuario,
    u.nombre as nombreUsuario,
    c.idProveedor,
    p.nombre as nombreProveedor,
    c.fecha,
    c.total
FROM compra c
INNER JOIN usuario u ON c.idUsuario = u.idUsuario
INNER JOIN proveedor p ON c.idProveedor = p.idProveedor
WHERE c.idUsuario = ?
ORDER BY c.fecha DESC
`

type GetComprasByUsuarioRow struct {
	Idcompra        int32     `json:"idcompra"`
	Idmetodopago    int32     `json:"idmetodopago"`
	Idusuario       int32     `json:"idusuario"`
	Nombreusuario   string    `json:"nombreusuario"`
	Idproveedor     int32     `json:"idproveedor"`
	Nombreproveedor string    `json:"nombreproveedor"`
	Fecha           time.Time `json:"fecha"`
	Total           string    `json:"total"`
}

func (q *Queries) GetComprasByUsuario(ctx context.Context, idusuario int32) ([]GetComprasByUsuarioRow, error) {
	rows, err := q.db.QueryContext(ctx, getComprasByUsuario, idusuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComprasByUsuarioRow
	for rows.Next() {
		var i GetComprasByUsuarioRow
		if err := rows.Scan(
			&i.Idcompra,
			&i.Idmetodopago,
			&i.Idusuario,
			&i.Nombreusuario,
			&i.Idproveedor,
			&i.Nombreproveedor,
			&i.Fecha,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
