// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: detallecompra.sql

package dto

import (
	"context"
	"database/sql"
)

const createDetalleCompra = `-- name: CreateDetalleCompra :execresult
INSERT INTO detallecompra (idCompra, idProducto, cantidad, precioCompra, subtotal)
VALUES (?, ?, ?, ?, ?)
`

type CreateDetalleCompraParams struct {
	Idcompra     int32  `json:"idcompra"`
	Idproducto   int32  `json:"idproducto"`
	Cantidad     int32  `json:"cantidad"`
	Preciocompra string `json:"preciocompra"`
	Subtotal     string `json:"subtotal"`
}

func (q *Queries) CreateDetalleCompra(ctx context.Context, arg CreateDetalleCompraParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDetalleCompra,
		arg.Idcompra,
		arg.Idproducto,
		arg.Cantidad,
		arg.Preciocompra,
		arg.Subtotal,
	)
}

const deleteDetalleCompra = `-- name: DeleteDetalleCompra :execresult
DELETE FROM detallecompra WHERE idDetalleCompra = ?
`

func (q *Queries) DeleteDetalleCompra(ctx context.Context, iddetallecompra int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDetalleCompra, iddetallecompra)
}

const getDetalleCompraById = `-- name: GetDetalleCompraById :one
SELECT iddetallecompra, idcompra, idproducto, cantidad, preciocompra, subtotal FROM detallecompra WHERE idDetalleCompra = ?
`

func (q *Queries) GetDetalleCompraById(ctx context.Context, iddetallecompra int32) (Detallecompra, error) {
	row := q.db.QueryRowContext(ctx, getDetalleCompraById, iddetallecompra)
	var i Detallecompra
	err := row.Scan(
		&i.Iddetallecompra,
		&i.Idcompra,
		&i.Idproducto,
		&i.Cantidad,
		&i.Preciocompra,
		&i.Subtotal,
	)
	return i, err
}

const getDetallesByCompraId = `-- name: GetDetallesByCompraId :many
SELECT 
    dc.iddetallecompra, dc.idcompra, dc.idproducto, dc.cantidad, dc.preciocompra, dc.subtotal,
    p.nombre as nombreProducto
FROM detallecompra dc
INNER JOIN producto p ON dc.idProducto = p.idProducto
WHERE dc.idCompra = ?
`

type GetDetallesByCompraIdRow struct {
	Iddetallecompra int32  `json:"iddetallecompra"`
	Idcompra        int32  `json:"idcompra"`
	Idproducto      int32  `json:"idproducto"`
	Cantidad        int32  `json:"cantidad"`
	Preciocompra    string `json:"preciocompra"`
	Subtotal        string `json:"subtotal"`
	Nombreproducto  string `json:"nombreproducto"`
}

func (q *Queries) GetDetallesByCompraId(ctx context.Context, idcompra int32) ([]GetDetallesByCompraIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getDetallesByCompraId, idcompra)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDetallesByCompraIdRow
	for rows.Next() {
		var i GetDetallesByCompraIdRow
		if err := rows.Scan(
			&i.Iddetallecompra,
			&i.Idcompra,
			&i.Idproducto,
			&i.Cantidad,
			&i.Preciocompra,
			&i.Subtotal,
			&i.Nombreproducto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDetalleCompra = `-- name: UpdateDetalleCompra :execresult
UPDATE detallecompra 
SET idProducto = ?, cantidad = ?, precioCompra = ?, subtotal = ?
WHERE idDetalleCompra = ?
`

type UpdateDetalleCompraParams struct {
	Idproducto      int32  `json:"idproducto"`
	Cantidad        int32  `json:"cantidad"`
	Preciocompra    string `json:"preciocompra"`
	Subtotal        string `json:"subtotal"`
	Iddetallecompra int32  `json:"iddetallecompra"`
}

func (q *Queries) UpdateDetalleCompra(ctx context.Context, arg UpdateDetalleCompraParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDetalleCompra,
		arg.Idproducto,
		arg.Cantidad,
		arg.Preciocompra,
		arg.Subtotal,
		arg.Iddetallecompra,
	)
}
