// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: detalleventa.sql

package dto

import (
	"context"
	"database/sql"
)

const createDetalleVenta = `-- name: CreateDetalleVenta :execresult
INSERT INTO detalleventa(
    idVenta,
    idProducto,
    cantidad,
    precioUnitario,
    subTotal
)
VALUES (?, ?, ?, ?, ?)
`

type CreateDetalleVentaParams struct {
	Idventa        int32  `json:"idventa"`
	Idproducto     int32  `json:"idproducto"`
	Cantidad       int32  `json:"cantidad"`
	Preciounitario string `json:"preciounitario"`
	Subtotal       string `json:"subtotal"`
}

func (q *Queries) CreateDetalleVenta(ctx context.Context, arg CreateDetalleVentaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDetalleVenta,
		arg.Idventa,
		arg.Idproducto,
		arg.Cantidad,
		arg.Preciounitario,
		arg.Subtotal,
	)
}

const deleteDetalleVenta = `-- name: DeleteDetalleVenta :execresult
DELETE FROM detalleventa
WHERE idDetalleVenta = ?
`

func (q *Queries) DeleteDetalleVenta(ctx context.Context, iddetalleventa int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDetalleVenta, iddetalleventa)
}

const getAllDetalleVenta = `-- name: GetAllDetalleVenta :many
SELECT iddetalleventa, idventa, idproducto, cantidad, preciounitario, subtotal FROM detalleventa
`

func (q *Queries) GetAllDetalleVenta(ctx context.Context) ([]Detalleventum, error) {
	rows, err := q.db.QueryContext(ctx, getAllDetalleVenta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Detalleventum
	for rows.Next() {
		var i Detalleventum
		if err := rows.Scan(
			&i.Iddetalleventa,
			&i.Idventa,
			&i.Idproducto,
			&i.Cantidad,
			&i.Preciounitario,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDetalleVentaById = `-- name: GetDetalleVentaById :one
SELECT iddetalleventa, idventa, idproducto, cantidad, preciounitario, subtotal FROM detalleventa
WHERE idDetalleVenta = ?
`

func (q *Queries) GetDetalleVentaById(ctx context.Context, iddetalleventa int32) (Detalleventum, error) {
	row := q.db.QueryRowContext(ctx, getDetalleVentaById, iddetalleventa)
	var i Detalleventum
	err := row.Scan(
		&i.Iddetalleventa,
		&i.Idventa,
		&i.Idproducto,
		&i.Cantidad,
		&i.Preciounitario,
		&i.Subtotal,
	)
	return i, err
}

const getDetalleVentaByVenta = `-- name: GetDetalleVentaByVenta :many
SELECT iddetalleventa, idventa, idproducto, cantidad, preciounitario, subtotal FROM detalleventa
WHERE idVenta = ?
`

func (q *Queries) GetDetalleVentaByVenta(ctx context.Context, idventa int32) ([]Detalleventum, error) {
	rows, err := q.db.QueryContext(ctx, getDetalleVentaByVenta, idventa)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Detalleventum
	for rows.Next() {
		var i Detalleventum
		if err := rows.Scan(
			&i.Iddetalleventa,
			&i.Idventa,
			&i.Idproducto,
			&i.Cantidad,
			&i.Preciounitario,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDetalleVenta = `-- name: UpdateDetalleVenta :execresult
UPDATE detalleventa
SET
    idProducto = ?,
    cantidad = ?,
    precioUnitario = ?,
    subTotal = ?
WHERE idDetalleVenta = ?
`

type UpdateDetalleVentaParams struct {
	Idproducto     int32  `json:"idproducto"`
	Cantidad       int32  `json:"cantidad"`
	Preciounitario string `json:"preciounitario"`
	Subtotal       string `json:"subtotal"`
	Iddetalleventa int32  `json:"iddetalleventa"`
}

func (q *Queries) UpdateDetalleVenta(ctx context.Context, arg UpdateDetalleVentaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDetalleVenta,
		arg.Idproducto,
		arg.Cantidad,
		arg.Preciounitario,
		arg.Subtotal,
		arg.Iddetalleventa,
	)
}
