// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dto

import (
	"database/sql"
	"time"
)

type Categoriaproducto struct {
	Idcategoriaproducto int32          `json:"idcategoriaproducto"`
	Nombre              string         `json:"nombre"`
	Descripcion         sql.NullString `json:"descripcion"`
}

type Cliente struct {
	Idcliente int32          `json:"idcliente"`
	Nombre    string         `json:"nombre"`
	Cedula    string         `json:"cedula"`
	Telefono  string         `json:"telefono"`
	Email     sql.NullString `json:"email"`
}

type Compra struct {
	Idcompra     int32     `json:"idcompra"`
	Idmetodopago int32     `json:"idmetodopago"`
	Idusuario    int32     `json:"idusuario"`
	Idproveedor  int32     `json:"idproveedor"`
	Fecha        time.Time `json:"fecha"`
	Total        string    `json:"total"`
}

type Detallecompra struct {
	Iddetallecompra int32  `json:"iddetallecompra"`
	Idcompra        int32  `json:"idcompra"`
	Idproducto      int32  `json:"idproducto"`
	Cantidad        int32  `json:"cantidad"`
	Preciocompra    string `json:"preciocompra"`
	Subtotal        string `json:"subtotal"`
}

type Detalleventum struct {
	Iddetalleventa int32  `json:"iddetalleventa"`
	Idventa        int32  `json:"idventa"`
	Idproducto     int32  `json:"idproducto"`
	Cantidad       int32  `json:"cantidad"`
	Preciounitario string `json:"preciounitario"`
	Subtotal       string `json:"subtotal"`
}

type Metodopago struct {
	Idmetodopago int32  `json:"idmetodopago"`
	Nombre       string `json:"nombre"`
	Descripcion  string `json:"descripcion"`
}

type Producto struct {
	Idproducto          int32          `json:"idproducto"`
	Idcategoriaproducto int32          `json:"idcategoriaproducto"`
	Idproveedor         int32          `json:"idproveedor"`
	Nombre              string         `json:"nombre"`
	Descripcion         string         `json:"descripcion"`
	Preciocompra        string         `json:"preciocompra"`
	Precioventa         string         `json:"precioventa"`
	Stock               int32          `json:"stock"`
	Imagenurl           sql.NullString `json:"imagenurl"`
}

type Proveedor struct {
	Idproveedor      int32          `json:"idproveedor"`
	Nombre           string         `json:"nombre"`
	Cedjuridica      string         `json:"cedjuridica"`
	Correo           string         `json:"correo"`
	Telefono         string         `json:"telefono"`
	Telefonocontacto sql.NullString `json:"telefonocontacto"`
	Nombrecontacto   sql.NullString `json:"nombrecontacto"`
}

type Rol struct {
	Idrol  int32  `json:"idrol"`
	Nombre string `json:"nombre"`
}

type Usuario struct {
	Idusuario  int32          `json:"idusuario"`
	Idrol      int32          `json:"idrol"`
	Nombre     string         `json:"nombre"`
	Contraseña string         `json:"contraseña"`
	Email      sql.NullString `json:"email"`
}

type Ventum struct {
	Idventa      int32          `json:"idventa"`
	Idmetodopago int32          `json:"idmetodopago"`
	Idusuario    int32          `json:"idusuario"`
	Idcliente    int32          `json:"idcliente"`
	Fecha        time.Time      `json:"fecha"`
	Subtotal     string         `json:"subtotal"`
	Descuento    sql.NullString `json:"descuento"`
	Iva          string         `json:"iva"`
	Total        string         `json:"total"`
}
