// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: producto.sql

package dto

import (
	"context"
	"database/sql"
)

const createProducto = `-- name: CreateProducto :execresult
INSERT INTO producto (
    idCategoriaProducto,
    idProveedor,
    nombre,
    descripcion,
    precioCompra,
    precioVenta,
    stock,
    imagenUrl
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProductoParams struct {
	Idcategoriaproducto int32          `json:"idcategoriaproducto"`
	Idproveedor         int32          `json:"idproveedor"`
	Nombre              string         `json:"nombre"`
	Descripcion         string         `json:"descripcion"`
	Preciocompra        string         `json:"preciocompra"`
	Precioventa         string         `json:"precioventa"`
	Stock               int32          `json:"stock"`
	Imagenurl           sql.NullString `json:"imagenurl"`
}

func (q *Queries) CreateProducto(ctx context.Context, arg CreateProductoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProducto,
		arg.Idcategoriaproducto,
		arg.Idproveedor,
		arg.Nombre,
		arg.Descripcion,
		arg.Preciocompra,
		arg.Precioventa,
		arg.Stock,
		arg.Imagenurl,
	)
}

const deleteProducto = `-- name: DeleteProducto :execresult
DELETE FROM producto
WHERE idProducto = ?
`

func (q *Queries) DeleteProducto(ctx context.Context, idproducto int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProducto, idproducto)
}

const getAllProductos = `-- name: GetAllProductos :many
SELECT p.idproducto, p.idcategoriaproducto, p.idproveedor, p.nombre, p.descripcion, p.preciocompra, p.precioventa, p.stock, p.imagenurl, c.nombre as nombreCategoria
FROM producto p
INNER JOIN categoriaproducto c ON p.idCategoriaProducto = c.idCategoriaProducto
`

type GetAllProductosRow struct {
	Idproducto          int32          `json:"idproducto"`
	Idcategoriaproducto int32          `json:"idcategoriaproducto"`
	Idproveedor         int32          `json:"idproveedor"`
	Nombre              string         `json:"nombre"`
	Descripcion         string         `json:"descripcion"`
	Preciocompra        string         `json:"preciocompra"`
	Precioventa         string         `json:"precioventa"`
	Stock               int32          `json:"stock"`
	Imagenurl           sql.NullString `json:"imagenurl"`
	Nombrecategoria     string         `json:"nombrecategoria"`
}

func (q *Queries) GetAllProductos(ctx context.Context) ([]GetAllProductosRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductosRow
	for rows.Next() {
		var i GetAllProductosRow
		if err := rows.Scan(
			&i.Idproducto,
			&i.Idcategoriaproducto,
			&i.Idproveedor,
			&i.Nombre,
			&i.Descripcion,
			&i.Preciocompra,
			&i.Precioventa,
			&i.Stock,
			&i.Imagenurl,
			&i.Nombrecategoria,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProductosWithDetails = `-- name: GetAllProductosWithDetails :many
SELECT 
    p.idproducto, p.idcategoriaproducto, p.idproveedor, p.nombre, p.descripcion, p.preciocompra, p.precioventa, p.stock, p.imagenurl,
    c.nombre as nombreCategoria,
    prov.nombre as nombreProveedor
FROM producto p
INNER JOIN categoriaproducto c ON p.idCategoriaProducto = c.idCategoriaProducto
INNER JOIN proveedor prov ON p.idProveedor = prov.idProveedor
`

type GetAllProductosWithDetailsRow struct {
	Idproducto          int32          `json:"idproducto"`
	Idcategoriaproducto int32          `json:"idcategoriaproducto"`
	Idproveedor         int32          `json:"idproveedor"`
	Nombre              string         `json:"nombre"`
	Descripcion         string         `json:"descripcion"`
	Preciocompra        string         `json:"preciocompra"`
	Precioventa         string         `json:"precioventa"`
	Stock               int32          `json:"stock"`
	Imagenurl           sql.NullString `json:"imagenurl"`
	Nombrecategoria     string         `json:"nombrecategoria"`
	Nombreproveedor     string         `json:"nombreproveedor"`
}

func (q *Queries) GetAllProductosWithDetails(ctx context.Context) ([]GetAllProductosWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductosWithDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductosWithDetailsRow
	for rows.Next() {
		var i GetAllProductosWithDetailsRow
		if err := rows.Scan(
			&i.Idproducto,
			&i.Idcategoriaproducto,
			&i.Idproveedor,
			&i.Nombre,
			&i.Descripcion,
			&i.Preciocompra,
			&i.Precioventa,
			&i.Stock,
			&i.Imagenurl,
			&i.Nombrecategoria,
			&i.Nombreproveedor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductoById = `-- name: GetProductoById :one
SELECT idproducto, idcategoriaproducto, idproveedor, nombre, descripcion, preciocompra, precioventa, stock, imagenurl FROM producto
WHERE idProducto = ?
`

func (q *Queries) GetProductoById(ctx context.Context, idproducto int32) (Producto, error) {
	row := q.db.QueryRowContext(ctx, getProductoById, idproducto)
	var i Producto
	err := row.Scan(
		&i.Idproducto,
		&i.Idcategoriaproducto,
		&i.Idproveedor,
		&i.Nombre,
		&i.Descripcion,
		&i.Preciocompra,
		&i.Precioventa,
		&i.Stock,
		&i.Imagenurl,
	)
	return i, err
}

const getProductosByCategoria = `-- name: GetProductosByCategoria :many
SELECT idproducto, idcategoriaproducto, idproveedor, nombre, descripcion, preciocompra, precioventa, stock, imagenurl FROM producto WHERE idCategoriaProducto = ?
`

func (q *Queries) GetProductosByCategoria(ctx context.Context, idcategoriaproducto int32) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, getProductosByCategoria, idcategoriaproducto)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.Idproducto,
			&i.Idcategoriaproducto,
			&i.Idproveedor,
			&i.Nombre,
			&i.Descripcion,
			&i.Preciocompra,
			&i.Precioventa,
			&i.Stock,
			&i.Imagenurl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductosByProveedor = `-- name: GetProductosByProveedor :many
SELECT idproducto, idcategoriaproducto, idproveedor, nombre, descripcion, preciocompra, precioventa, stock, imagenurl FROM producto WHERE idProveedor = ?
`

func (q *Queries) GetProductosByProveedor(ctx context.Context, idproveedor int32) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, getProductosByProveedor, idproveedor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.Idproducto,
			&i.Idcategoriaproducto,
			&i.Idproveedor,
			&i.Nombre,
			&i.Descripcion,
			&i.Preciocompra,
			&i.Precioventa,
			&i.Stock,
			&i.Imagenurl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductoById = `-- name: SearchProductoById :one
SELECT idproducto, idcategoriaproducto, idproveedor, nombre, descripcion, preciocompra, precioventa, stock, imagenurl FROM producto WHERE idProducto = ?
`

func (q *Queries) SearchProductoById(ctx context.Context, idproducto int32) (Producto, error) {
	row := q.db.QueryRowContext(ctx, searchProductoById, idproducto)
	var i Producto
	err := row.Scan(
		&i.Idproducto,
		&i.Idcategoriaproducto,
		&i.Idproveedor,
		&i.Nombre,
		&i.Descripcion,
		&i.Preciocompra,
		&i.Precioventa,
		&i.Stock,
		&i.Imagenurl,
	)
	return i, err
}

const searchProductoByName = `-- name: SearchProductoByName :many
SELECT idproducto, idcategoriaproducto, idproveedor, nombre, descripcion, preciocompra, precioventa, stock, imagenurl FROM producto WHERE nombre LIKE ? OR descripcion LIKE ?
`

type SearchProductoByNameParams struct {
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
}

func (q *Queries) SearchProductoByName(ctx context.Context, arg SearchProductoByNameParams) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, searchProductoByName, arg.Nombre, arg.Descripcion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.Idproducto,
			&i.Idcategoriaproducto,
			&i.Idproveedor,
			&i.Nombre,
			&i.Descripcion,
			&i.Preciocompra,
			&i.Precioventa,
			&i.Stock,
			&i.Imagenurl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProducto = `-- name: UpdateProducto :execresult
UPDATE producto
SET
    idCategoriaProducto = ?,
    idProveedor = ?,
    nombre = ?,
    descripcion = ?,
    precioCompra = ?,
    precioVenta = ?,
    stock = ?,
    imagenUrl = ?
WHERE idProducto = ?
`

type UpdateProductoParams struct {
	Idcategoriaproducto int32          `json:"idcategoriaproducto"`
	Idproveedor         int32          `json:"idproveedor"`
	Nombre              string         `json:"nombre"`
	Descripcion         string         `json:"descripcion"`
	Preciocompra        string         `json:"preciocompra"`
	Precioventa         string         `json:"precioventa"`
	Stock               int32          `json:"stock"`
	Imagenurl           sql.NullString `json:"imagenurl"`
	Idproducto          int32          `json:"idproducto"`
}

func (q *Queries) UpdateProducto(ctx context.Context, arg UpdateProductoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProducto,
		arg.Idcategoriaproducto,
		arg.Idproveedor,
		arg.Nombre,
		arg.Descripcion,
		arg.Preciocompra,
		arg.Precioventa,
		arg.Stock,
		arg.Imagenurl,
		arg.Idproducto,
	)
}

const updateProductoStock = `-- name: UpdateProductoStock :execresult
UPDATE producto SET stock = ? WHERE idProducto = ?
`

type UpdateProductoStockParams struct {
	Stock      int32 `json:"stock"`
	Idproducto int32 `json:"idproducto"`
}

func (q *Queries) UpdateProductoStock(ctx context.Context, arg UpdateProductoStockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProductoStock, arg.Stock, arg.Idproducto)
}

const updateProductoStockCompra = `-- name: UpdateProductoStockCompra :execresult
UPDATE producto SET stock = stock + ? WHERE idProducto = ?
`

type UpdateProductoStockCompraParams struct {
	Stock      int32 `json:"stock"`
	Idproducto int32 `json:"idproducto"`
}

func (q *Queries) UpdateProductoStockCompra(ctx context.Context, arg UpdateProductoStockCompraParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProductoStockCompra, arg.Stock, arg.Idproducto)
}
