// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proveedor.sql

package dto

import (
	"context"
	"database/sql"
)

const createProveedores = `-- name: CreateProveedores :execresult
INSERT INTO proveedor (nombre, cedJuridica, correo, telefono, telefonoContacto, nombreContacto) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateProveedoresParams struct {
	Nombre           string         `json:"nombre"`
	Cedjuridica      string         `json:"cedjuridica"`
	Correo           string         `json:"correo"`
	Telefono         string         `json:"telefono"`
	Telefonocontacto sql.NullString `json:"telefonocontacto"`
	Nombrecontacto   sql.NullString `json:"nombrecontacto"`
}

func (q *Queries) CreateProveedores(ctx context.Context, arg CreateProveedoresParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProveedores,
		arg.Nombre,
		arg.Cedjuridica,
		arg.Correo,
		arg.Telefono,
		arg.Telefonocontacto,
		arg.Nombrecontacto,
	)
}

const deleteProveedores = `-- name: DeleteProveedores :execresult
DELETE FROM proveedor WHERE idProveedor = ?
`

func (q *Queries) DeleteProveedores(ctx context.Context, idproveedor int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProveedores, idproveedor)
}

const getAllProveedores = `-- name: GetAllProveedores :many
SELECT idproveedor, nombre, cedjuridica, correo, telefono, telefonocontacto, nombrecontacto FROM proveedor
`

func (q *Queries) GetAllProveedores(ctx context.Context) ([]Proveedor, error) {
	rows, err := q.db.QueryContext(ctx, getAllProveedores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proveedor
	for rows.Next() {
		var i Proveedor
		if err := rows.Scan(
			&i.Idproveedor,
			&i.Nombre,
			&i.Cedjuridica,
			&i.Correo,
			&i.Telefono,
			&i.Telefonocontacto,
			&i.Nombrecontacto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProveedoresByCedJuridica = `-- name: GetProveedoresByCedJuridica :one
SELECT idproveedor, nombre, cedjuridica, correo, telefono, telefonocontacto, nombrecontacto FROM proveedor WHERE cedJuridica = ?
`

func (q *Queries) GetProveedoresByCedJuridica(ctx context.Context, cedjuridica string) (Proveedor, error) {
	row := q.db.QueryRowContext(ctx, getProveedoresByCedJuridica, cedjuridica)
	var i Proveedor
	err := row.Scan(
		&i.Idproveedor,
		&i.Nombre,
		&i.Cedjuridica,
		&i.Correo,
		&i.Telefono,
		&i.Telefonocontacto,
		&i.Nombrecontacto,
	)
	return i, err
}

const getProveedoresById = `-- name: GetProveedoresById :one
SELECT idproveedor, nombre, cedjuridica, correo, telefono, telefonocontacto, nombrecontacto FROM proveedor WHERE idProveedor = ?
`

func (q *Queries) GetProveedoresById(ctx context.Context, idproveedor int32) (Proveedor, error) {
	row := q.db.QueryRowContext(ctx, getProveedoresById, idproveedor)
	var i Proveedor
	err := row.Scan(
		&i.Idproveedor,
		&i.Nombre,
		&i.Cedjuridica,
		&i.Correo,
		&i.Telefono,
		&i.Telefonocontacto,
		&i.Nombrecontacto,
	)
	return i, err
}

const getProveedoresByNombre = `-- name: GetProveedoresByNombre :many
SELECT idproveedor, nombre, cedjuridica, correo, telefono, telefonocontacto, nombrecontacto FROM proveedor WHERE nombre LIKE ?
`

func (q *Queries) GetProveedoresByNombre(ctx context.Context, nombre string) ([]Proveedor, error) {
	rows, err := q.db.QueryContext(ctx, getProveedoresByNombre, nombre)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proveedor
	for rows.Next() {
		var i Proveedor
		if err := rows.Scan(
			&i.Idproveedor,
			&i.Nombre,
			&i.Cedjuridica,
			&i.Correo,
			&i.Telefono,
			&i.Telefonocontacto,
			&i.Nombrecontacto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProveedores = `-- name: UpdateProveedores :execresult
UPDATE proveedor SET nombre = ?, cedJuridica = ?, correo = ?, telefono = ?, telefonoContacto = ?, nombreContacto = ? WHERE idProveedor = ?
`

type UpdateProveedoresParams struct {
	Nombre           string         `json:"nombre"`
	Cedjuridica      string         `json:"cedjuridica"`
	Correo           string         `json:"correo"`
	Telefono         string         `json:"telefono"`
	Telefonocontacto sql.NullString `json:"telefonocontacto"`
	Nombrecontacto   sql.NullString `json:"nombrecontacto"`
	Idproveedor      int32          `json:"idproveedor"`
}

func (q *Queries) UpdateProveedores(ctx context.Context, arg UpdateProveedoresParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProveedores,
		arg.Nombre,
		arg.Cedjuridica,
		arg.Correo,
		arg.Telefono,
		arg.Telefonocontacto,
		arg.Nombrecontacto,
		arg.Idproveedor,
	)
}
