// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuario.sql

package dto

import (
	"context"
	"database/sql"
)

const createUsuario = `-- name: CreateUsuario :execresult
INSERT INTO usuario (idRol, nombre, contraseña, email)
VALUES (?, ?, ?, ?)
`

type CreateUsuarioParams struct {
	Idrol      int32          `json:"idrol"`
	Nombre     string         `json:"nombre"`
	Contraseña string         `json:"contraseña"`
	Email      sql.NullString `json:"email"`
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUsuario,
		arg.Idrol,
		arg.Nombre,
		arg.Contraseña,
		arg.Email,
	)
}

const deleteUsuario = `-- name: DeleteUsuario :execresult
DELETE FROM usuario
WHERE idUsuario = ?
`

func (q *Queries) DeleteUsuario(ctx context.Context, idusuario int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUsuario, idusuario)
}

const getAllUsuarios = `-- name: GetAllUsuarios :many
SELECT idusuario, idrol, nombre, contraseña, email FROM usuario
`

func (q *Queries) GetAllUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.Idusuario,
			&i.Idrol,
			&i.Nombre,
			&i.Contraseña,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsuarioByEmail = `-- name: GetUsuarioByEmail :one
SELECT idusuario, idrol, nombre, contraseña, email FROM usuario
WHERE email = ?
`

func (q *Queries) GetUsuarioByEmail(ctx context.Context, email sql.NullString) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuarioByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.Idusuario,
		&i.Idrol,
		&i.Nombre,
		&i.Contraseña,
		&i.Email,
	)
	return i, err
}

const getUsuarioById = `-- name: GetUsuarioById :one
SELECT idusuario, idrol, nombre, contraseña, email FROM usuario
WHERE idUsuario = ?
`

func (q *Queries) GetUsuarioById(ctx context.Context, idusuario int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuarioById, idusuario)
	var i Usuario
	err := row.Scan(
		&i.Idusuario,
		&i.Idrol,
		&i.Nombre,
		&i.Contraseña,
		&i.Email,
	)
	return i, err
}

const searchUsuarioByEmail = `-- name: SearchUsuarioByEmail :many
SELECT idusuario, idrol, nombre, contraseña, email FROM usuario WHERE email LIKE ?
`

func (q *Queries) SearchUsuarioByEmail(ctx context.Context, email sql.NullString) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, searchUsuarioByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.Idusuario,
			&i.Idrol,
			&i.Nombre,
			&i.Contraseña,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsuarioByName = `-- name: SearchUsuarioByName :many
SELECT idusuario, idrol, nombre, contraseña, email FROM usuario WHERE email LIKE ?
`

func (q *Queries) SearchUsuarioByName(ctx context.Context, email sql.NullString) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, searchUsuarioByName, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.Idusuario,
			&i.Idrol,
			&i.Nombre,
			&i.Contraseña,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsuario = `-- name: UpdateUsuario :execresult
UPDATE usuario
SET idRol = ?, nombre = ?, contraseña = ?, email = ?
WHERE idUsuario = ?
`

type UpdateUsuarioParams struct {
	Idrol      int32          `json:"idrol"`
	Nombre     string         `json:"nombre"`
	Contraseña string         `json:"contraseña"`
	Email      sql.NullString `json:"email"`
	Idusuario  int32          `json:"idusuario"`
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUsuario,
		arg.Idrol,
		arg.Nombre,
		arg.Contraseña,
		arg.Email,
		arg.Idusuario,
	)
}
