// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venta.sql

package dto

import (
	"context"
	"database/sql"
	"time"
)

const createVenta = `-- name: CreateVenta :execresult
INSERT INTO venta(
    idMetodoPago,
    idUsuario,
    idCliente,
    fecha,
    subTotal,
    descuento,
    IVA,
    total
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateVentaParams struct {
	Idmetodopago int32          `json:"idmetodopago"`
	Idusuario    int32          `json:"idusuario"`
	Idcliente    int32          `json:"idcliente"`
	Fecha        time.Time      `json:"fecha"`
	Subtotal     string         `json:"subtotal"`
	Descuento    sql.NullString `json:"descuento"`
	Iva          string         `json:"iva"`
	Total        string         `json:"total"`
}

func (q *Queries) CreateVenta(ctx context.Context, arg CreateVentaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createVenta,
		arg.Idmetodopago,
		arg.Idusuario,
		arg.Idcliente,
		arg.Fecha,
		arg.Subtotal,
		arg.Descuento,
		arg.Iva,
		arg.Total,
	)
}

const deleteVenta = `-- name: DeleteVenta :execresult
DELETE FROM venta
WHERE idVenta = ?
`

func (q *Queries) DeleteVenta(ctx context.Context, idventa int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteVenta, idventa)
}

const getAllVentas = `-- name: GetAllVentas :many
SELECT idventa, idmetodopago, idusuario, idcliente, fecha, subtotal, descuento, iva, total FROM venta
`

func (q *Queries) GetAllVentas(ctx context.Context) ([]Ventum, error) {
	rows, err := q.db.QueryContext(ctx, getAllVentas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ventum
	for rows.Next() {
		var i Ventum
		if err := rows.Scan(
			&i.Idventa,
			&i.Idmetodopago,
			&i.Idusuario,
			&i.Idcliente,
			&i.Fecha,
			&i.Subtotal,
			&i.Descuento,
			&i.Iva,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVentaById = `-- name: GetVentaById :one
SELECT idventa, idmetodopago, idusuario, idcliente, fecha, subtotal, descuento, iva, total FROM venta
WHERE idVenta = ?
`

func (q *Queries) GetVentaById(ctx context.Context, idventa int32) (Ventum, error) {
	row := q.db.QueryRowContext(ctx, getVentaById, idventa)
	var i Ventum
	err := row.Scan(
		&i.Idventa,
		&i.Idmetodopago,
		&i.Idusuario,
		&i.Idcliente,
		&i.Fecha,
		&i.Subtotal,
		&i.Descuento,
		&i.Iva,
		&i.Total,
	)
	return i, err
}

const updateVenta = `-- name: UpdateVenta :execresult
UPDATE venta
SET
    idMetodoPago = ?,
    idUsuario = ?,
    idCliente = ?,
    fecha = ?,
    subTotal = ?,
    descuento = ?,
    IVA = ?,
    total = ?
WHERE idVenta = ?
`

type UpdateVentaParams struct {
	Idmetodopago int32          `json:"idmetodopago"`
	Idusuario    int32          `json:"idusuario"`
	Idcliente    int32          `json:"idcliente"`
	Fecha        time.Time      `json:"fecha"`
	Subtotal     string         `json:"subtotal"`
	Descuento    sql.NullString `json:"descuento"`
	Iva          string         `json:"iva"`
	Total        string         `json:"total"`
	Idventa      int32          `json:"idventa"`
}

func (q *Queries) UpdateVenta(ctx context.Context, arg UpdateVentaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateVenta,
		arg.Idmetodopago,
		arg.Idusuario,
		arg.Idcliente,
		arg.Fecha,
		arg.Subtotal,
		arg.Descuento,
		arg.Iva,
		arg.Total,
		arg.Idventa,
	)
}
